### ISSUE TITLE
Fix class names in PHPDoc comments for use in PHPStorm

### ISSUE THREAD

**Issue by PowerGamer1** [jstewmc/rtf#1]
Code snippet from `Document.php`:

``` PHP
namespace Jstewmc\Rtf;
class Document
{
    /**
     * @return  Jstewmc\Rtf\Element\Group
     */
    public function getRoot()
    {
        return $this->root;
    }
```

Class name in PHPDoc comment such as `@return  Jstewmc\Rtf\Element\Group` in the example above should be written as `@return  \Jstewmc\Rtf\Element\Group` (notice leading backslash) or `@return  Element\Group` (as if you were specifying that class name inside the actual PHP code, not the comment). As it stands now PHPStorm IDE does not understand the syntax and does not provide the code completion functionality for return values of your class methods.

**Comment by jstewmc** [comment]
Hi @PowerGamer1, 

Thank you for the well-documented issue, and I'm sorry for the trouble.

It's a little funny. I have been doing those annotations wrong for years! For some dumb reason, I thought PHPDocumentor wanted them as fully qualified class names starting from the global namespace, like a `use` statement. Unfortunately, that is not the case! 

My co-worker @javabudd pointed out my mistake a few weeks ago. 

I don't think it's a huge rush, but I'm sure it's annoying. If I can catch a few hours in the upcoming weeks, I'll try and fix those annotations (of course, they are wrong in _all_ of my libraries, eek!).
