### ISSUE TITLE
Just trying to iterate

### ISSUE THREAD

**Issue by ggutierrezbarbeito** [jstewmc/rtf#10]
I´m trying to iterate from the root just to find one parameter, maybe a /*PARAM*/ param value in RTF file and change it for the DB values, can u help me to do that???
Best regards
Thanks

**Comment by jstewmc** [comment]
Hi @ggutierrezbarbeito, I'm not sure how you would search for a parameter. That's a use case I had not anticipated. If it's still an issue and you can share your RTF, re-open the issue, and I'll try to help you brainstorm some ideas.
