### ISSUE TITLE
Cannot get the lexer/parser to work

### ISSUE THREAD

**Issue by wetmarble** [jstewmc/rtf#4]
Hi,

I installed via composer and I'm having a very difficult time getting this to work. I'm not very familiar with namespaces and I suspect that this is the source of my problem.

This is my code taken from the examples:
````php
require __ROOTBASE__ . '/vendor/autoload.php';
use Jstewmc\Rtf;

// create a text stream
$stream = new \Jstewmc\Stream\Text('{foo {\b bar\b0}}');

// create the lexer
$lexer = Lexer();

// lex the source into tokens
$tokens = $lexer->lex($stream);

// loop through the tokens and echo them to the screen for this example
// in the real world, you would pass them to a parser
//
foreach ($tokens as $token) {
    if ($token instanceof Token\Group\Open) {
        echo "{";
    } elseif ($token instanceof Token\Group\Close) {
        echo "}";   
    } elseif ($token instanceof Token\Control\Word) {
        echo "\\{$token->getWord()}{$token->getParameter()}";
    } elseif ($token instanceof Token\Control\Symbol) {
        echo "\\{$token->getSymbol()}{$token->getParameter()}";
    } elseif ($token instanceof Token\Text) {
        echo \"$token->getText()\";
    }
}

// create the parser
$parser = new Parser();

// parse the tokens into the parse tree
$root = $parser->parse($tokens);

// look into the parse tree
echo get_class($root);                   // prints "Jstewmc\Rtf\Element\Group"
echo get_class($root->getFirstChild());  // prints "Jstewmc\Rtf\Element\Text"
echo get_class($root->getLastChild());   // prints "Jstewmc\Rtf\Element\Group"
````

And I simply get a 500 internal server error.

Any help would be appreciated.

**Comment by jstewmc** [comment]
Hi @wetmarble! Sorry you're having trouble with the library buddy. 

Try prefixing the classnames `Token\Group\Open`, `Token\Group\Close`, etc with `Rtf` so they become `Rtf\Token\Group\Open`, `Rtf\Token\Group\Close`, etc. 

You've imported the `Jstewmc\Rtf` namespace as `Rtf` with the `use` statement. _Without_ the prefix on those `Token` classes, PHP is looking in the global namespace for them. However, it can't find them. _With_ the prefix, PHP will look in the `Jstewmc\Rtf` namespace, where they are.

Let me know if that doesn't help. 

PS - It's entirely possible my examples have the incorrect namespaces. I was once in your namespace-newbie shoes haha!
