### ISSUE TITLE
question: can i use code without composer?

### ISSUE THREAD

**Issue by boomsya** [jstewmc/rtf#5]
it is real to use like this?:

```
require_once(JPATH_COMPONENT .DS. 'rtf'.DS.'Document.php');
$document = new Document(file_get_contents($rtffile));
echo $document->write('html');  // prints "<section style=""><p style="">..."
```

**Comment by jstewmc** [comment]
Hi @boomsya,

Hmm, it's going to be a pain to use this library without Composer and its autoloader. There are probably well over 100 classes in here, and you'll have to `require` or `include` each one before your first call to `new Document()`!

You might try registering your own [PSR-4](http://www.php-fig.org/psr/psr-4/) autoloader? I did that once when my lead wouldn't let me use Composer. I foxed him haha. Here are a few [examples](http://www.php-fig.org/psr/psr-4/examples/) that may help.
