### ISSUE TITLE
I wonder why...

### ISSUE THREAD

**Issue by Okcuoglu** [jstewmc/rtf#7]
More of a Question or I'm wondering if you will. 

Following list is my include/ require list for a result that's more than disappointing. Perhaps you can help me ? 

This is what i needed to include to get a rtf interpretation run. The interpretation worked without any correct formats and fonts from the original rtf. How is this possible? 

require "../../CAStandards/includes/server/Jstewmc/Chunker/Chunker.php";
require "../../CAStandards/includes/server/Jstewmc/Chunker/Text.php";
require "../../CAStandards/includes/server/Jstewmc/Stream/Stream.php";

require "../../CAStandards/includes/server/Jstewmc/Document.php";
require "../../CAStandards/includes/server/Jstewmc/Parser.php";
require "../../CAStandards/includes/server/Jstewmc/Lexer.php";
require "../../CAStandards/includes/server/Jstewmc/Renderer.php";
require "../../CAStandards/includes/server/Jstewmc/Style.php";
require "../../CAStandards/includes/server/Jstewmc/Writer.php";

require "../../CAStandards/includes/server/Jstewmc/State/State.php";
require "../../CAStandards/includes/server/Jstewmc/State/Section.php";
require "../../CAStandards/includes/server/Jstewmc/State/Paragraph.php";
require "../../CAStandards/includes/server/Jstewmc/State/Character.php";
require "../../CAStandards/includes/server/Jstewmc/State/Document.php";

require "../../CAStandards/includes/server/Jstewmc/Element/Element.php";
require "../../CAStandards/includes/server/Jstewmc/Element/Text.php";
require "../../CAStandards/includes/server/Jstewmc/Element/Group.php";

require "../../CAStandards/includes/server/Jstewmc/Element/Control/Control.php";
require "../../CAStandards/includes/server/Jstewmc/Element/Control/Word/Word.php";
require "../../CAStandards/includes/server/Jstewmc/Element/Control/Symbol/Symbol.php";

require "../../CAStandards/includes/server/Jstewmc/Token/Token.php";
require "../../CAStandards/includes/server/Jstewmc/Token/Text.php";
require "../../CAStandards/includes/server/Jstewmc/Token/Other.php";

require "../../CAStandards/includes/server/Jstewmc/Token/Group/Group.php";
require "../../CAStandards/includes/server/Jstewmc/Token/Group/Open.php";
require "../../CAStandards/includes/server/Jstewmc/Token/Group/Close.php";

require "../../CAStandards/includes/server/Jstewmc/Token/Control/Control.php";
require "../../CAStandards/includes/server/Jstewmc/Token/Control/Symbol.php";
require "../../CAStandards/includes/server/Jstewmc/Token/Control/Word.php";

use Jstewmc\Chunker;
use Jstewmc\Text;
use Jstewmc\Stream;

use Jstewmc\Rtf\Token\Token;
use Jstewmc\Rtf\Token\Control\Word;
use Jstewmc\Rtf\Token\Group\Group;
use Jstewmc\Rtf\Token\Group\Open;
use Jstewmc\Rtf\State\State;

use Jstewmc\Rtf\Document;
use Jstewmc\Rtf\Lexer;

**Comment by jstewmc** [comment]
Hi @Okcuoglu, 

I'm sorry you're disappoinated with your results. I'm sure creating that list of require statements was a lot of work!

This library is definitely better at simple documents. The RTF-CRE specification that I built this library for hardly has any formatting. It's pretty much straight text documents. 

I'm curious what you mean by "interpretation". Is that a lexing, a parsing, or a rendering? If you inspect the Lexer's output, does it have tokens for your fonts and formats? 

If your document defines fonts and formats in the document's head group, those might be lost during rendering. The lexer should pick them up, but, if I remember correctly, the renderer may ignore them. It's been a while, but I seem to remember that being an issue. That sort of stuff was just more complex than what I needed.

**Comment by Okcuoglu** [comment]
HI Jack, 

sorry that my issue description was a little rough. No affence. At first, it's great you wrote that libs and shared them with us. I was researching for about a week to find a appropriate lib like this which converts in both ways rtf<->html. When i've found yours, i was really hopeful, later disappointed, because there where no fonts or anything which was parsed (that's b.t.w. what i meant with interpretation :) ) but also the header wasn't correctly parsed. The Word "arial" was still written in the parsed text although it was the font definition. it's a great job, you did here, but sadfully not useable for me. 

Thank you for your fast reply. Your Library has really potential to get a Standard, used world wide if you will, but needs to be reassambled. Good luck for that.
