### ISSUE TITLE
How to use this library with Codeigniter framework

### ISSUE THREAD

**Issue by Asim-Khadim** [jstewmc/rtf#8]
Dear Sir,

             Can you please guide me How to embed rtf Library with codeigniter ?
I will be thankful to you .

**Comment by jstewmc** [comment]
Hi @Asim-Khadim, my apologies for the five-year-late reply! If you're still using this library, you should follow the README's new installation steps and use composer to include this library into your code like any other PHP third-party library. Thanks!
